name: Python package

on:
  push:
    tags:
      - "v*.*.*"
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4

      - name: Publish package distributions to PyPI
        run: pdm publish -u __token__ -P ${{ secrets.PYPI_API_TOKEN }}