name: Release

on:
  push:
    tags:
      - v*
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Publish python poetry package
        uses: JRubics/poetry-publish@v1.12
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}